### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by anthr76** [stakewise/helm-charts#85]
Currently the images in the operator chart need support for arm64. Should stakewise and it's operators raise this upstream or package them themselves. This will support pure arm64 clusters and multi-arch clusters reducing power contraints. I wouldl ike to enter being operator. I will enter testnet using nodeSelector but I would like to improve my power usage. 

The current images requiring arm64 support.

- [ ] `gcr.io/prysmaticlabs/prysm/validator`
https://github.com/stakewise/helm-charts/blob/7eabdc4a8c1708d86910e02a0da789966b415a6b/charts/operator/values.yaml#L67-L69
- [ ] `europe-west4-docker.pkg.dev/stakewiselabs/public/validator-init`
https://github.com/stakewise/helm-charts/blob/7eabdc4a8c1708d86910e02a0da789966b415a6b/charts/operator/values.yaml#L80-L81

**Comment by unxnn** [comment]
Hey @anthr76! Thank you for the proposal! We have updated our `validator-init` image, now it contains amd64/arm64 versions. As for client images, it is better to contact the developers of these clients directly and ask them to build a version for the arm, also, you can always build and use your own image in our charts. We don't want to build our own client validator images due to trust and security reasons, it's always better to use official registries to get clients or build one yourself.

**Comment by anthr76** [comment]
Sounds good. Incase anyone here passes by this issue in the future the only image that should be left is prysm which a issue was opened and seems to be acted against. https://github.com/prysmaticlabs/prysm/issues/10119
